### ISSUE TITLE
[Contrib] Script to generate `podspec` file for new versions of your components / [now: inconsistency in wiki doc]

### ISSUE THREAD

**Issue by AliSoftware** [CocoaPods/CocoaPods#1382]
> [EDIT] This script is in fact useless once you know that `pod push` exists. But there is still an inconsistency in the wiki doc as `pod push` is not the way suggested in the doc (which explains why I thought this script was useful). See [this comment below](#issuecomment-24870223)

---

I have written a [script to **automatically generate the podspec for updates of my components** here](https://gist.github.com/AliSoftware/6624144).

I think this script might be useful for a lot of us (maybe even adding it into "~/.cocoapods" by default when we install CP? Or translate it in ruby and create a `pod spec upgrade` command or whatnot?) to avoid repetitive tasks when releasing new versions.
### When can it be useful
- you already have a component referenced in CocoaPods (you already have at least one podspec)
- You create a new version of your component and want to create the podspec for the new version, which is basically the same as the previous podspec but with just the version field updated
### How to use
- tag your component repository (and push the tag to your remote)
- run `genspec.sh <pathtorepo>` in your terminal

> Tip: If you use [SourceTree](http://www.sourcetreeapp.com/), you can even add a "Custom Action" to add access it easily directly from SourceTree!
### What it does
- Find the latest tag you added on your repo
- Duplicate the latest podspec you have for your component in `~/.cocoapods/repos/` in the appropriate folder named after this tag
- Change the `s.version` line of this new podspec to the name of the new tag
- Commit it on the cocoapods repo, ready to be pushed (or amended)
### TODO
- [ ] Add error managment (directory is not a git repo, no tag found, no previous podspec for the component to copy, …)
- [ ] Change the `:git` of the `s.source` line as well for those who don't use `:tag => s.version.to_s` like I do
- [ ] `pod spec lint` the podspec before creating the commit
- [ ] The name of the component (basename for podspec file) is deduced from the name of the directory where you cloned your working copy on your machine. Maybe add an optional argument to specify the component name if different from the working copy directory name?
