### ISSUE TITLE
Allow custom xcconfigs to extend definitions in generated files

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#2467]
## Goal

Allow users to use custom xcconfig files, which import the generated xcconfigs and make further definitions based on the values contained in those, as injecting manual integrated dependencies.

This is based on a previous disucssion in https://github.com/CocoaPods/CocoaPods/issues/1212.
## Tasks
- [ ] namespace the build settings in user / aggregate target xcconfigs to allow to easily override them
- [ ] define a base xcconfig to inherit the common settings of the installation to reduce SCM noise
  - [ ] `PODS_ROOT`
  - [ ] `GCC_PREPROCESSOR_DEFINITIONS`, `OTHER_SWIFT_FLAGS`
  - [ ] `LD_RUNPATH_SEARCH_PATHS`, `EMBEDDED_CONTENT_CONTAINS_SWIFT`
- [x] append `$(inherited)` to the value of each setting
## Example

```
HEADER_SEARCH_PATHS  = "${PODS_ROOT}/Headers"
```

should be:

```
PODS_HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers"
HEADER_SEARCH_PATHS = ${PODS_HEADER_SEARCH_PATHS}
```

**Comment by segiddins** [comment]
Note that we can't add `$(inherited)` to singular build settings -- only the plural ones

**Comment by nevir** [comment]
FWIW, here's a bit of a hacktastic workaround:

```rb
# CocoaPods-managed variables that you should support.
#
# If CocoaPods adds one not in this list, an error will be thrown to let you know.
EXPECTED_KEYS = ['FRAMEWORK_SEARCH_PATHS', 'GCC_PREPROCESSOR_DEFINITIONS', 'HEADER_SEARCH_PATHS', 'OTHER_CFLAGS', 'OTHER_LDFLAGS', 'PODS_ROOT'].sort

post_install do |installer|
  driver_pod = installer.aggregate_targets.find { |t| t.label == 'Pods-Driver' }
  driver_pod.native_target.build_configurations.each do |config|
    config_path = driver_pod.xcconfig_path(config.name)
    config_data = config_path.read

    keys = config_data.each_line.map {|l| l.sub(/(^.*?)\s*=.*$/, '\1').strip }
    unknown_keys = keys - EXPECTED_KEYS
    if unknown_keys.size > 0
      raise "Encountered unknown xcconfig key(s) (from CocoaPods): #{unknown_keys.join(', ')}"
    end

    # Ensure that every value is prefixed with PODS_
    config_data.gsub! /^(?!PODS_)(.*)$/, 'PODS_\1'

    File.write(config_path, config_data)
  end
end
```

**Comment by mrackwitz** [comment]
I updated this issue's title and description to reflect the goal of the proposed change. Furthermore this is only relevant to the user / aggregate target xcconfigs and not to pod target xcconfigs, as those aren't shared with any user targets and so shouldn't be subject to any overwrites.

Please note: What was proposed in #2387, can't be covered anymore with the way pod targets are generated, as those definitions have to be generated individually per target.

**Comment by revolter** [comment]
So what's the status? I came from #1212 but found no solution here...

**Comment by pronebird** [comment]
Same here. How do you do this?

**Comment by ManWithBear** [comment]
In Cocoapods v1.6.0 `native_target` have been removed.
Updated script looks like:
```ruby
    installer.target_installation_results.each do |result|
      result.each do |name, installation_result|
        next unless installation_result.native_target and name.start_with? 'Pods-'
        next if TARGETS_TO_IGNORE_KEYS.include? name
        target = installation_result.target
        installation_result.native_target.build_configurations.each do |config|
          config_path = target.xcconfig_path(config.name)
          config_data = config_path.read

          keys = config_data.each_line.map {|l| l.sub(/(^.*?)\s*=.*$/, '\1').strip }

          unknown_keys = keys - EXPECTED_KEYS
          if unknown_keys.size > 0
            raise "Encountered unknown xcconfig key(s) (from CocoaPods): #{unknown_keys.join(', ')} in #{target.label} - #{config.name} "
          end

          # Ensure that every value is prefixed with PODS_
          config_data.gsub! /^(?!PODS_)(.*)$/, 'PODS_\1'

          File.write(config_path, config_data)
        end
      end
    end
```

**Comment by kateinoigakukun** [comment]
In v1.7.5 I found a workaround to add xcconfig definition.

```ruby
class Pod::Target::BuildSettings
  PLURAL_SETTINGS = PLURAL_SETTINGS + ["PODS_OTHER_LDFLAGS"]
  define_build_settings_method :pods_other_ldflags, :build_setting => true, :memoized => true do
    other_ldflags
  end
end

target 'App' do
  use_frameworks!
  pod 'AFNetworking'
end
```

This produces below ↓ 
```
...
OTHER_LDFLAGS = $(inherited) -framework "AFNetworking" -framework "SystemConfiguration"
PODS_OTHER_LDFLAGS = $(inherited) -framework "AFNetworking" -framework "SystemConfiguration"
...
```

**Comment by fbartho** [comment]
@ManWithBear does your workaround still work -- this year? I think CocoaPods as of 2020 no longer prefixes the target names with `Pods-` :(

**Comment by ManWithBear** [comment]
@fbartho we still using it in our project
