### ISSUE TITLE
Support target de-integration

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#2471]
###### TODO

- [ ] Remove the support files generated for the target
- [ ] Remove the xcconfigs from the user project
- [ ] Remove the dependency on the umbrella target

**Comment by segiddins** [comment]
@kylef ping ^

**Comment by AliSoftware** [comment]
In addition to target de-integration, we should also implement configuration de-integration, namely if `xcodeproj 'Foo', 'Beta' => :release` gets added, then removed, I'm not sure we then do everything needed to remove the consequences of that stuff?

**Comment by AliSoftware** [comment]
Also, remove unused `Pods/Resources` resource files (upcoming from #3263)

**Comment by segiddins** [comment]
@kylef can you please do the work necessary to make `pod deintegrate` a default plugin?

**Comment by manuyavuz** [comment]
@segiddins I think this issue is completed so we could close it?

**Comment by kylef** [comment]
The issue was not about the deintegrate plugin, but if I remove a target from my Podfile and do `pod install` it would get cleaned up. Was this also implemented?

**Comment by segiddins** [comment]
Yes.
