### ISSUE TITLE
Feedback from GitHub meta-issue

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#5005]
These are the immediate action items taken from #4989.

Main Actions:

- [x] Use GitHub API to determine if we need to update #5001 
- [x] Switch away from shallow clones of the Specs repo #5016
- [x] Support switching to not updating the Specs Repo by default #5004 
- [x] Convert to using a sub-folder structure in the Specs repo #5002

**Comment by segiddins** [comment]
Once #5004 is addressed, we will be releasing a beta 6, and I will work on adding support for #5002 to ship in a beta 7, though the final migration likely won't happen for a while.

**Comment by segiddins** [comment]
1.0.0.beta.6 has support for all but the new directory structure -- this ought to help a bit!

**Comment by segiddins** [comment]
We've written up a post-mortem of the original issue and the steps taken to mitigate: http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/.
